
services:
  go-webserver:
    build: ./backend
    container_name: go_webserver
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - questdb
    environment:
      KAFKA_BROKER: kafka:9092
      QUESTDB_URL: http://questdb:9000    

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "9000:9000"
      - "8812:8812"

  frontend:
    build: ./frontend
    container_name: svelte_frontend
    ports:
      - "5000:5000"
    depends_on:
      - go-webserver
